### ISSUE TITLE
Couldn't load plugin

### ISSUE THREAD

**Issue by Vixienne20dec** [Sploder-Saptarshi/Sploder-Launcher#1]
I ran the bat file and installed all the necessary stuff and it still says Couldn't load plugin, is there anyway I can troubleshoot this?

**Comment by Sploder-Saptarshi** [comment]
May I please know who you are on the Sploder discord server?

Also, you must build it first since running it in dev mode won't run flash.

To build it, run yarn dist

**Comment by Vixienne20dec** [comment]
Hey, I'm not on the Discord yet but I've gotten it running successfully a
while ago, thank you!

**Comment by Sploder-Saptarshi** [comment]
Congrats on getting it to run! Join the discord server at https://discord.gg/sploder

Make sure to replace your flash binaries with CleanFlash ones. They have about 2 years worth of updates.
