### ISSUE TITLE
Auto update system?

### ISSUE THREAD

**Issue by johnnybob78** [Sploder-Saptarshi/Sploder-Launcher#2]
How about a warning pop-up or something that automatically tells you whenever a new update is out?

**Comment by Sploder-Saptarshi** [comment]
I just use my webserver for that, this was not supposed to be open-source lol.
<img width="618" alt="image" src="https://github.com/Sploder-Saptarshi/Sploder-Launcher/assets/85979829/107aa07f-86c1-46b7-b06e-a7837340a73f">

**Comment by Sploder-Saptarshi** [comment]
What's your username on sploder by the way?

**Comment by Sploder-Saptarshi** [comment]
Closed due to inactivity...
